### ISSUE TITLE
Fix build error

### ISSUE THREAD

**Issue by nyxrobotics** [sbgisen/gsoap-onvif#1]
**概要**
ビルドエラーを修正し、サンプルプログラムが動くように変更する

**修正案**
- [ ] Cmakeの修正
- [ ] 不要なファイルの削除
- [ ] フォルダ構成の整理
- [ ] 中国語→英語翻訳

**Comment by nyxrobotics** [comment]
- OpenSSLの型変換エラー
```bash
gsoap-onvif/factory/3rdparty/ssigonvif/onvif/src/gsoap/mecevp.c:274:71: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_CIPHER_CTX {aka evp_cipher_ctx_st}’
   data->ctx = (EVP_CIPHER_CTX*)SOAP_MALLOC(soap, sizeof(EVP_CIPHER_CTX));
```
- 参考：[https://github.com/Netflix/dynomite/issues/510](Dynomite doesn't compile with OpenSSL 1.1)

**Comment by nyxrobotics** [comment]
- CmakeにCursesパッケージ追加
```
find_package(Curses REQUIRED)
```

```
include_directories(
	${CMAKE_CURRENT_LIST_DIR}/include
    ${CURSES_INCLUDE_DIR}
)
```

```
target_link_libraries(zoom_tea wl
	${OpenCV_LIBS}
	${CURSES_LIBRARIES}
)
```
